"""Seed data for SkillSeed: careers, future-skills, missions, and discover questions."""

CAREERS = [
    # Traditional
    {"id": "engineer", "name": "Engineer", "category": "traditional", "emoji": "⚙️",
     "tagline": "Build the machines and systems that power our world.",
     "day_in_life": "Sketch ideas, prototype, test, iterate, and collaborate with teammates to solve real problems.",
     "skills": ["Problem solving", "Math", "Design thinking", "Persistence"],
     "starter_mission": "Design a paper prototype of a gadget that solves a problem at home."},
    {"id": "doctor", "name": "Doctor", "category": "traditional", "emoji": "🩺",
     "tagline": "Heal people and champion lifelong wellbeing.",
     "day_in_life": "Meet patients, listen to their stories, examine, diagnose, and guide them toward healing.",
     "skills": ["Empathy", "Biology", "Focus", "Communication"],
     "starter_mission": "Interview a family member about a time they felt cared for by a doctor."},
    {"id": "lawyer", "name": "Lawyer", "category": "traditional", "emoji": "⚖️",
     "tagline": "Fight for fairness with reason and words.",
     "day_in_life": "Read cases, meet clients, prepare arguments, and stand up for what's right.",
     "skills": ["Debate", "Reading", "Logic", "Writing"],
     "starter_mission": "Pick a school rule you disagree with and write a one-page argument to change it."},
    {"id": "teacher", "name": "Teacher", "category": "traditional", "emoji": "📚",
     "tagline": "Spark curiosity and change lives, one student at a time.",
     "day_in_life": "Plan lessons, present ideas playfully, mentor students, and keep growing yourself.",
     "skills": ["Storytelling", "Patience", "Creativity", "Empathy"],
     "starter_mission": "Teach a friend one thing you learned this week in under 3 minutes."},
    # Modern
    {"id": "creator", "name": "Content Creator", "category": "modern", "emoji": "🎬",
     "tagline": "Turn your ideas, humor, and skills into a global audience.",
     "day_in_life": "Brainstorm, shoot, edit, publish, and talk to your community every single day.",
     "skills": ["Storytelling", "Editing", "Consistency", "Authenticity"],
     "starter_mission": "Record a 60-second video explaining something you love."},
    {"id": "founder", "name": "Entrepreneur", "category": "modern", "emoji": "🚀",
     "tagline": "Spot a problem worth solving and build the solution.",
     "day_in_life": "Talk to users, sketch products, sell, hire, break, rebuild — repeat.",
     "skills": ["Curiosity", "Resilience", "Selling", "Focus"],
     "starter_mission": "Find one problem in your daily life and sketch a simple business that solves it."},
    {"id": "designer", "name": "UX Designer", "category": "modern", "emoji": "🎨",
     "tagline": "Make technology feel human, delightful, and easy.",
     "day_in_life": "Interview users, sketch flows, prototype in Figma, test, and refine again and again.",
     "skills": ["Empathy", "Visual thinking", "Curiosity", "Attention to detail"],
     "starter_mission": "Redesign your school's timetable on paper so it's easier to read."},
    {"id": "freelancer", "name": "Freelancer", "category": "modern", "emoji": "💼",
     "tagline": "Sell one skill you love to clients across the world.",
     "day_in_life": "Pitch, deliver great work, manage clients, learn constantly, and keep your calendar full.",
     "skills": ["Self-management", "Communication", "One deep skill", "Discipline"],
     "starter_mission": "Pick one skill you'd freelance in — draw a poster, edit a reel, teach chess."},
    # AI
    {"id": "ai_engineer", "name": "AI Engineer", "category": "ai", "emoji": "🤖",
     "tagline": "Teach machines to think, see, and speak.",
     "day_in_life": "Read papers, wrangle data, train models, evaluate, and ship intelligent products.",
     "skills": ["Math", "Coding", "Curiosity", "Systems thinking"],
     "starter_mission": "Chat with an AI for 10 minutes about a topic you're curious about."},
    {"id": "prompt_engineer", "name": "Prompt Engineer", "category": "ai", "emoji": "🧠",
     "tagline": "Craft words that unlock the power of AI models.",
     "day_in_life": "Experiment with prompts, evaluate outputs, and design AI workflows.",
     "skills": ["Language", "Logic", "Creativity", "Testing"],
     "starter_mission": "Write 3 different prompts to make an AI explain gravity to a 5-year-old."},
    {"id": "ai_researcher", "name": "AI Researcher", "category": "ai", "emoji": "🔬",
     "tagline": "Discover new frontiers in machine intelligence.",
     "day_in_life": "Ask 'what if,' design experiments, share findings, and push the science forward.",
     "skills": ["Math", "Reading papers", "Patience", "Writing"],
     "starter_mission": "Read a one-page article on how AI is helping doctors, then explain it in your own words."},
    # Creative
    {"id": "musician", "name": "Musician", "category": "creative", "emoji": "🎧",
     "tagline": "Move people through sound and rhythm.",
     "day_in_life": "Practice, compose, collaborate, record, and perform.",
     "skills": ["Ear training", "Discipline", "Emotion", "Collaboration"],
     "starter_mission": "Record a 30-second beat or melody on your phone using any app."},
    {"id": "writer", "name": "Writer", "category": "creative", "emoji": "✍️",
     "tagline": "Turn thoughts into worlds that others can live in.",
     "day_in_life": "Read a lot, write a little every day, edit, and share your voice.",
     "skills": ["Reading", "Observation", "Vocabulary", "Empathy"],
     "starter_mission": "Write a 100-word story about a day in your favorite place."},
    {"id": "game_designer", "name": "Game Designer", "category": "creative", "emoji": "🎮",
     "tagline": "Design worlds and rules that people love to play in.",
     "day_in_life": "Sketch mechanics, prototype, playtest with friends, and polish the fun.",
     "skills": ["Storytelling", "Systems thinking", "Playfulness", "Iteration"],
     "starter_mission": "Design a 5-minute card game using only a deck of cards."},
    {"id": "filmmaker", "name": "Filmmaker", "category": "creative", "emoji": "🎥",
     "tagline": "Tell stories the world can see, hear, and feel.",
     "day_in_life": "Write scripts, direct actors, shoot scenes, edit, and share your vision.",
     "skills": ["Story", "Visual eye", "Leadership", "Editing"],
     "starter_mission": "Shoot a 30-second silent story on your phone with just visuals."},
]

SKILLS = [
    {"id": "ai_literacy", "name": "AI Literacy", "emoji": "🤖",
     "description": "Learn how AI actually works — and how to use it as your creative superpower.",
     "milestones": ["Chat with AI daily", "Understand prompts", "Generate an image", "Build a mini AI project"]},
    {"id": "financial_literacy", "name": "Financial Literacy", "emoji": "💰",
     "description": "Money is a skill. Learn to earn it, grow it, and use it wisely.",
     "milestones": ["Track spending 7 days", "Understand saving vs investing", "Learn what a stock is", "Make your first budget"]},
    {"id": "communication", "name": "Communication", "emoji": "🗣️",
     "description": "Speak, write, and pitch your ideas with confidence.",
     "milestones": ["Speak up in a group", "Record a 60s video", "Give a mini talk", "Pitch an idea to family"]},
    {"id": "coding", "name": "Coding", "emoji": "💻",
     "description": "Turn ideas into working software. The most valuable skill of your generation.",
     "milestones": ["Print 'Hello World'", "Build a calculator", "Create a webpage", "Ship a mini app"]},
    {"id": "creativity", "name": "Creativity", "emoji": "🎨",
     "description": "Train your idea muscle. Combine, remix, and make what's never been made.",
     "milestones": ["Sketch daily 7 days", "Remix a favorite thing", "Make something for a friend", "Share your art"]},
]

MISSIONS = [
    {"id": "m_dream_app", "title": "Design your dream app", "emoji": "📱", "difficulty": "easy",
     "duration_min": 20, "growth_points": 30,
     "trait_impacts": {"creativity": 6, "confidence": 3},
     "reflection_prompt": "What did you notice about your own ideas while designing this?",
     "description": "Sketch on paper (or in your phone's notes) the app you wish existed. 3 screens. One key feature."},
    {"id": "m_ai_image", "title": "Generate your first AI image", "emoji": "🖼️", "difficulty": "easy",
     "duration_min": 15, "growth_points": 25,
     "trait_impacts": {"creativity": 5, "curiosity": 4},
     "reflection_prompt": "What surprised you about what the AI made?",
     "description": "Use any free AI tool to generate an image of your future self doing what you love."},
    {"id": "m_interview_grand", "title": "Interview your grandparents", "emoji": "👵", "difficulty": "medium",
     "duration_min": 30, "growth_points": 40,
     "trait_impacts": {"communication": 6, "curiosity": 5, "resilience": 2},
     "reflection_prompt": "What did they say that you've been thinking about since?",
     "description": "Ask them 5 questions about their childhood dreams. Write down the most surprising answer."},
    {"id": "m_explain_ai", "title": "Explain AI to a friend", "emoji": "🧠", "difficulty": "easy",
     "duration_min": 10, "growth_points": 20,
     "trait_impacts": {"communication": 5, "confidence": 3},
     "reflection_prompt": "What was hardest to put into words?",
     "description": "In your own words, explain to a friend or sibling what AI actually is. Under 2 minutes."},
    {"id": "m_solve_problem", "title": "Spot a problem worth solving", "emoji": "🔍", "difficulty": "medium",
     "duration_min": 25, "growth_points": 40,
     "trait_impacts": {"creativity": 5, "curiosity": 5, "leadership": 3},
     "reflection_prompt": "Who else would benefit if you solved this?",
     "description": "Walk around your home for 15 minutes. Note one small annoying problem. Sketch a solution."},
    {"id": "m_60s_video", "title": "Record a 60-second video", "emoji": "🎬", "difficulty": "medium",
     "duration_min": 20, "growth_points": 35,
     "trait_impacts": {"communication": 6, "confidence": 6},
     "reflection_prompt": "What did you learn watching yourself back?",
     "description": "Talk to camera for 60 seconds about something you genuinely love. Watch it back."},
    {"id": "m_save_50", "title": "Track your money for a week", "emoji": "💸", "difficulty": "easy",
     "duration_min": 5, "growth_points": 20,
     "trait_impacts": {"resilience": 4, "curiosity": 3},
     "reflection_prompt": "Where did your money actually go — vs where you thought?",
     "description": "For 7 days, note every rupee you spend. On day 7, look at where it went."},
    {"id": "m_teach_friend", "title": "Teach a friend one thing", "emoji": "🎓", "difficulty": "easy",
     "duration_min": 15, "growth_points": 25,
     "trait_impacts": {"communication": 4, "leadership": 5, "confidence": 4},
     "reflection_prompt": "How did teaching change what you thought you knew?",
     "description": "Teach a friend one skill or fact you know well. Notice how you feel after."},
]

# The six growth traits. Order matters — used for rendering.
TRAITS = [
    {"id": "curiosity",     "name": "Curiosity",     "emoji": "🔭", "color": "#38BDF8",
     "description": "Your appetite to wonder, ask, and follow the thread."},
    {"id": "creativity",    "name": "Creativity",    "emoji": "🎨", "color": "#F472B6",
     "description": "Your ability to imagine, combine, and make what didn't exist."},
    {"id": "confidence",    "name": "Confidence",    "emoji": "✨", "color": "#FBBF24",
     "description": "Your comfort taking up space and trusting your voice."},
    {"id": "communication", "name": "Communication", "emoji": "🗣️", "color": "#10B981",
     "description": "Your power to make people feel and understand what you mean."},
    {"id": "leadership",    "name": "Leadership",    "emoji": "🧭", "color": "#6366F1",
     "description": "Your knack for bringing others along on an idea."},
    {"id": "resilience",    "name": "Resilience",    "emoji": "🌱", "color": "#A855F7",
     "description": "Your quiet strength when things get uncomfortable."},
]

DISCOVER_QUESTIONS = [
    {"id": "q1", "prompt": "When you have free time, what pulls you in the most?",
     "options": ["Building or fixing things", "Reading, writing, or telling stories",
                 "Drawing, music, or making art", "Solving puzzles or numbers",
                 "Talking with people and helping them"]},
    {"id": "q2", "prompt": "What kind of problems light you up?",
     "options": ["Big real-world problems", "Creative or artistic challenges",
                 "Technical or logical puzzles", "Helping-people problems",
                 "I'm not sure yet"]},
    {"id": "q3", "prompt": "How do you learn best?",
     "options": ["By doing and building", "By reading and thinking",
                 "By watching and copying", "By talking it out",
                 "A little of everything"]},
    {"id": "q4", "prompt": "Which of these sounds most fun for a full day?",
     "options": ["Coding an app or robot", "Filming or editing a video",
                 "Writing a story or comic", "Running a small business",
                 "Learning something totally new"]},
]
